service: tinyflix-back

provider:
  name: aws
  runtime: python3.9
  region: us-central-1
  environment:
    MOVIE_TABLE: Movies
    MOVIE_BUCKET: movie-bucket

functions:
  uploadMovie:
    handler: lambdas/upload_movie.lambda_handler
    events:
      - http:
          path: upload
          method: post

  downloadMovie:
    handler: lambdas/download_movie.lambda_handler
    events:
      - http:
          path: download
          method: get

  deleteMovie:
    handler: lambdas/delete_movie.lambda_handler
    events:
      - http:
          path: delete
          method: delete

resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Movies
        AttributeDefinitions:
          - AttributeName: MovieID
            AttributeType: S
        KeySchema:
          - AttributeName: MovieID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: movie-bucket

plugins:
  - serverless-python-requirements

